[global]
   workgroup = HOME
   server string = Samba Server
   server role = standalone server

   # Логи
   log file = /var/log/samba/%m.log
   max log size = 50
   logging = syslog

   # Безпека
   security = user
   map to guest = Bad User
   guest account = nobody

   # Протоколи (сучасні)
   server min protocol = SMB2
   server max protocol = SMB3

   # Шари користувачів
   unix charset = UTF-8

   # Usershare
   usershare allow guests = yes


[roman-pc]
   path = /home/roman
   valid users = roman
   read only = no

   create mask = 0664
   directory mask = 2775


[public]
   path = /home/roman/Public
   guest ok = yes
   read only = no

   create mask = 0666
   directory mask = 0777
