include themes/Nordic.conf
# include themes/Galaxy.conf
# include themes/Alucard.conf
# include themes/Bright_Lights.conf
# include themes/Apprentice.conf
# include themes/Solarized_Darcula.conf

# Fonts
font_family JetbrainsMono Nerd Font
font_size 16.0

# Window
background_opacity 0.90
background_blur 10
window_margin 5
remember_window_size no
initial_window_width 100c
initial_window_height 34c


# Cursor customization
# cursor green
cursor yellow
# cursor_shape beam
# cursor_trail 2

###
confirm_os_window_close 0
