# Перевизначаємо налаштування для bash-language-server
[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

# Вимикаємо рекурсивні зовнішні джерела для shellcheck та обмежуємо патерни файлів
[language-server.bash-language-server.config]
shellcheckExternalSources = false
backgroundAnalysisMaxFiles = 10
includeAllWorkspaceSymbols = false
globPattern = "**/*.{sh,inc,bash,command}"

[language-server.bash-language-server.config.shfmt]
path = "shfmt"
languageDialect = "bash"

# Прив'язуємо оновлений сервер до мови bash
[[language]]
name = "bash"
language-servers = ["bash-language-server"]
