# ============================================================
# ДИРЕКТОРІЇ
# ============================================================

BACKUP_DIRS=(
    ".config/fzf"
    ".config/helix"
    ".config/nvim"
    ".config/nvim.nvchad"
    ".config/wezterm"
    ".config/kitty"
    ".config/eza"
    ".config/Kvantum"
    ".config/mc"
    ".config/starship"
    ".config/television"
    ".config/yazi"
    ".config/zed"
    ".local/share/fonts"
)

# ============================================================
# ФАЙЛИ
# ============================================================

BACKUP_FILES=(
    ".zshrc"
    ".zsh_alias.zsh"
    ".zsh_path.zsh"
    ".p10k_my.zsh"
    ".p10k_my_nordic_v1.zsh"
    ".fonts.conf"
)

# ============================================================
# ВИКЛЮЧЕННЯ
# ============================================================

EXCLUDE_PATTERNS=(
    ".git"
    "*.tmp"
    "*.swp"
)
