#!/usr/bin/env bash

# ============================================================
# СПИСКИ ПАКЕТІВ INSTALLER PACKAGES V1.5
# ============================================================
# Тут зберігаються тільки списки пакетів.
# Прив'язка масивів до модулів знаходиться у modules.conf.
# ============================================================

BASE_PACKAGES=(
    base-devel
    git
    curl
    wget
    rsync
    unzip
    zip
    tar
    p7zip
    unace
    unrar
    unzip
)

CLI_PACKAGES=(
    bat
    eza
    fd
    ripgrep
    fzf
    jq
    tree
    htop
    btop
    neovim
    xclip
    wl-clipboard
    fastfetch
    mc
    kitty
    wezterm
    transmission-qt
)

SHELL_PACKAGES=(
    zsh
    zsh-completions
    zsh-syntax-highlighting
    zsh-autocomplete
    zsh-autosuggestions
    starship
)

DEV_PACKAGES=(
    gcc
    make
    cmake
    python
    python-pip
    nodejs
    npm
    shellcheck
)

DOCKER_PACKAGES=(
    docker
    docker-compose
)

NETWORK_PACKAGES=(
    bind
    iperf3
    nmap
    traceroute
    whois
    tcpdump
    openssh
    ethtool
)

OFFICE_PACKAGES=(
    libreoffice-still
    libreoffice-still-uk    
)

KDE_PACKAGES=(
    ark
    packagekit-qt5
    libappindicator-gtk2
    colord-kde
    kaccounts-integration
    kaccounts-providers
    kdeconnect
    kdenetwork-filesharing
    kwalletmanager
    dolphin-plugins
    kompare kimageformats
    qt5-imageformats
    kdesdk-thumbnailers
    ffmpegthumbs
    taglib
    audiocd-kio
    kio-gdrive
    kvantum
    kcalc

)

DESKTOP_PACKAGES=()

DESKTOP_AUR_PACKAGES=(
    google-chrome
)

IMAGE_PACKAGES=(
    imagemagick
    gwenview
    gimp
    inkscape
    okular
)

MULTIMEDIA_PACKAGES=(
    vlc
    ffmpeg
    ffmpegthumbnailer
    vlc
    vlc-plugins-all
)

MULTIMEDIA_AUR_PACKAGES=(
    deadbeef
)
